/**
 * S3-compatible API controller.
 *
 * All routes are registered under /s3 prefix (from module).
 * S3 clients should use endpoint: http://host:port/s3
 *
 * Implements:
 *   - GET /          → ListBuckets
 *   - HEAD /:bucket  → HeadBucket
 *   - PUT /:bucket   → CreateBucket
 *   - DELETE /:bucket → DeleteBucket
 *   - GET /:bucket   → ListObjectsV2
 *   - POST /:bucket  → DeleteObjects (bulk)
 *   - PUT /:bucket/* → PutObject
 *   - GET /:bucket/* → GetObject
 *   - HEAD /:bucket/* → HeadObject
 *   - DELETE /:bucket/* → DeleteObject
 */

import type { FastifyInstance } from "fastify";
import { customAlphabet } from "nanoid";
import { verifyS3Auth } from "../../common/s3/auth.js";
import {
  errorXml,
  listAllMyBucketsXml,
  listObjectsV2Xml,
  deleteResultXml,
  type S3BucketEntry,
  type S3ObjectEntry,
} from "../../common/s3/xml.js";
import {
  createBucket,
  listBuckets,
  getBucketByName,
  deleteBucket,
  uploadObject,
  getObjectMeta,
  deleteObject,
  getFilePath,
} from "../storage/storage.service.js";
import { getDb } from "../../common/db/client.js";
import { objects } from "../../common/db/schema.js";
import { eq, and, like, asc } from "drizzle-orm";

const reqIdGen = customAlphabet("ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789", 16);

export function registerS3Routes(app: FastifyInstance) {
  // ── Always parse body as raw Buffer for S3 (overrides JSON/text parsers) ────
  // text/plain is parsed as string by Fastify by default → byteLength wrong
  app.addContentTypeParser("application/json", { parseAs: "buffer" }, (_req, body, done) => {
    done(null, body);
  });
  app.addContentTypeParser("text/plain", { parseAs: "buffer" }, (_req, body, done) => {
    done(null, body);
  });
  app.addContentTypeParser("application/xml", { parseAs: "buffer" }, (_req, body, done) => {
    done(null, body);
  });
  app.addContentTypeParser("text/xml", { parseAs: "buffer" }, (_req, body, done) => {
    done(null, body);
  });

  // ── S3 Auth hook ──────────────────────────────────────────────────────────────
  app.addHook("preHandler", async (req, reply) => {
    const requestId = reqIdGen();
    reply.header("x-amz-request-id", requestId);
    reply.header("Server", "MoroS3");

    const authResult = await verifyS3Auth(
      req.method,
      req.url.split("?")[0],
      req.url.includes("?") ? req.url.split("?")[1] : "",
      req.headers as Record<string, string | string[] | undefined>,
      req.body as Buffer | undefined,
    );

    if (!authResult.authenticated) {
      reply
        .code(403)
        .header("Content-Type", "application/xml")
        .send(
          errorXml("AccessDenied", authResult.error || "Access Denied", {
            RequestId: requestId,
          }),
        );
    }
  });

  // ── GET / → ListBuckets ─────────────────────────────────────────────────────
  app.get("/", async (_req, reply) => {
    const result = await listBuckets();
    const entries: S3BucketEntry[] = result.items.map((b) => ({
      name: b.name,
      createdAt: b.createdAt,
    }));
    return reply
      .code(200)
      .header("Content-Type", "application/xml")
      .send(listAllMyBucketsXml(entries));
  });


  // HEAD /:bucket and HEAD /:bucket/* are auto-generated by Fastify from GET routes

  // ── PUT /:bucket → CreateBucket ─────────────────────────────────────────────
  app.put("/:bucket", async (req, reply) => {
    const { bucket } = req.params as { bucket: string };

    try {
      await createBucket({ name: bucket, isPublic: false });
      return reply.code(200).header("Location", `/${bucket}`).send();
    } catch (err: unknown) {
      const msg = err instanceof Error ? err.message : "Error";
      if (msg.includes("already exists")) {
        return reply
          .code(409)
          .header("Content-Type", "application/xml")
          .send(errorXml("BucketAlreadyOwnedByYou", "Your previous request to create the named bucket succeeded."));
      }
      return reply
        .code(500)
        .header("Content-Type", "application/xml")
        .send(errorXml("InternalError", msg));
    }
  });

  // ── DELETE /:bucket → DeleteBucket ──────────────────────────────────────────
  app.delete("/:bucket", async (req, reply) => {
    const { bucket } = req.params as { bucket: string };

    try {
      await deleteBucket(bucket, false);
      return reply.code(204).send();
    } catch (err: unknown) {
      const msg = err instanceof Error ? err.message : "Error";
      if (msg.includes("not found")) {
        return reply
          .code(404)
          .header("Content-Type", "application/xml")
          .send(errorXml("NoSuchBucket", "The specified bucket does not exist."));
      }
      if (msg.includes("not empty")) {
        return reply
          .code(409)
          .header("Content-Type", "application/xml")
          .send(errorXml("BucketNotEmpty", "The bucket you tried to delete is not empty."));
      }
      return reply
        .code(500)
        .header("Content-Type", "application/xml")
        .send(errorXml("InternalError", msg));
    }
  });

  // ── GET /:bucket → ListObjectsV2 ───────────────────────────────────────────
  app.get("/:bucket", async (req, reply) => {
    const { bucket } = req.params as { bucket: string };
    const query = req.query as Record<string, string>;

    const b = await getBucketByName(bucket);
    if (!b) {
      return reply
        .code(404)
        .header("Content-Type", "application/xml")
        .send(errorXml("NoSuchBucket", "The specified bucket does not exist.", { BucketName: bucket }));
    }

    const prefix = query.prefix ?? "";
    const delimiter = query.delimiter ?? "";
    const maxKeys = Math.min(parseInt(query["max-keys"] ?? "1000", 10), 1000);
    const contToken = query["continuation-token"];

    let startAfter = "";
    if (contToken) {
      try { startAfter = Buffer.from(contToken, "base64").toString("utf-8"); } catch { /* ignore */ }
    }
    if (query["start-after"]) startAfter = query["start-after"];

    const db = getDb();
    const conditions = [eq(objects.bucketId, b.id)];
    if (prefix) conditions.push(like(objects.key, `${prefix}%`));

    const allRows = await db
      .select()
      .from(objects)
      .where(and(...conditions))
      .orderBy(asc(objects.key))
      .all();

    const filtered = startAfter ? allRows.filter((r) => r.key > startAfter) : allRows;

    const commonPrefixes = new Set<string>();
    const items: S3ObjectEntry[] = [];

    for (const row of filtered) {
      if (delimiter) {
        const suffix = row.key.slice(prefix.length);
        const delimIdx = suffix.indexOf(delimiter);
        if (delimIdx >= 0) {
          commonPrefixes.add(prefix + suffix.slice(0, delimIdx + 1));
          continue;
        }
      }
      items.push({
        key: row.key,
        lastModified: row.updatedAt,
        etag: row.etag,
        size: row.size,
      });
    }

    const isTruncated = items.length > maxKeys;
    const truncatedItems = items.slice(0, maxKeys);
    const nextToken = isTruncated
      ? Buffer.from(truncatedItems[truncatedItems.length - 1].key).toString("base64")
      : undefined;

    return reply
      .code(200)
      .header("Content-Type", "application/xml")
      .send(
        listObjectsV2Xml({
          bucketName: bucket,
          prefix,
          delimiter,
          maxKeys,
          items: truncatedItems,
          commonPrefixes: Array.from(commonPrefixes).sort(),
          isTruncated,
          continuationToken: contToken,
          nextContinuationToken: nextToken,
          keyCount: truncatedItems.length + commonPrefixes.size,
        }),
      );
  });

  // ── POST /:bucket?delete → DeleteObjects (bulk) ─────────────────────────────
  app.post("/:bucket", async (req, reply) => {
    const { bucket } = req.params as { bucket: string };
    const query = req.query as Record<string, string>;

    if ("delete" in query || query["delete"] === "") {
      const body = (req.body as Buffer).toString("utf-8");
      const keyMatches = body.match(/<Key>([^<]+)<\/Key>/g);
      if (!keyMatches) {
        return reply.code(200).header("Content-Type", "application/xml").send(deleteResultXml([], []));
      }

      const keys = keyMatches.map((m) => {
        const match = m.match(/<Key>([^<]+)<\/Key>/);
        return match ? match[1] : "";
      }).filter(Boolean);

      const deleted = [];
      const errors = [];

      for (const key of keys) {
        try {
          await deleteObject(bucket, key);
          deleted.push({ key });
        } catch (err: unknown) {
          const msg = err instanceof Error ? err.message : "Error";
          errors.push({ key, code: "InternalError", message: msg });
        }
      }

      return reply
        .code(200)
        .header("Content-Type", "application/xml")
        .send(deleteResultXml(deleted, errors));
    }

    return reply
      .code(400)
      .header("Content-Type", "application/xml")
      .send(errorXml("InvalidRequest", "Unknown POST operation"));
  });

  // ── PUT /:bucket/* → PutObject ──────────────────────────────────────────────
  app.put("/:bucket/*", async (req, reply) => {
    const { bucket } = req.params as { bucket: string };
    const key = (req.params as Record<string, string>)["*"];
    if (!key) {
      return reply
        .code(400)
        .header("Content-Type", "application/xml")
        .send(errorXml("InvalidArgument", "Object key is required"));
    }

    try {
      const ct = (req.headers["content-type"] as string) || "application/octet-stream";
      const body = (req.body as Buffer) ?? Buffer.alloc(0);
      const result = await uploadObject(bucket, key, body, ct);
      return reply.code(200).header("ETag", `"${result.etag}"`).send();
    } catch (err: unknown) {
      const msg = err instanceof Error ? err.message : "Error";
      if (msg.includes("Bucket not found")) {
        return reply
          .code(404)
          .header("Content-Type", "application/xml")
          .send(errorXml("NoSuchBucket", "The specified bucket does not exist."));
      }
      return reply
        .code(500)
        .header("Content-Type", "application/xml")
        .send(errorXml("InternalError", msg));
    }
  });

  // ── GET /:bucket/* → GetObject ──────────────────────────────────────────────
  app.get("/:bucket/*", async (req, reply) => {
    const { bucket } = req.params as { bucket: string };
    const key = (req.params as Record<string, string>)["*"];
    if (!key) {
      return reply
        .code(400)
        .header("Content-Type", "application/xml")
        .send(errorXml("InvalidArgument", "Object key is required"));
    }

    const meta = await getObjectMeta(bucket, key);
    if (!meta) {
      return reply
        .code(404)
        .header("Content-Type", "application/xml")
        .send(errorXml("NoSuchKey", "The specified key does not exist.", { Key: key }));
    }

    const filePath = getFilePath(bucket, key);
    if (!filePath) {
      return reply
        .code(404)
        .header("Content-Type", "application/xml")
        .send(errorXml("NoSuchKey", "The specified key does not exist.", { Key: key }));
    }

    const file = Bun.file(filePath);
    const buf = Buffer.from(await file.arrayBuffer());

    return reply
      .code(200)
      .header("Content-Type", meta.contentType)
      .header("Content-Length", meta.size)
      .header("ETag", `"${meta.etag}"`)
      .header("Last-Modified", new Date(meta.updatedAt).toUTCString())
      .header("Accept-Ranges", "bytes")
      .send(buf);
  });


  // ── DELETE /:bucket/* → DeleteObject ────────────────────────────────────────
  app.delete("/:bucket/*", async (req, reply) => {
    const { bucket } = req.params as { bucket: string };
    const key = (req.params as Record<string, string>)["*"];
    if (!key) return reply.code(400).send();

    try {
      await deleteObject(bucket, key);
    } catch {
      // S3 returns 204 even if key doesn't exist
    }
    return reply.code(204).send();
  });
}
